### ISSUE TITLE
application:openURL:options: in AppDelegate is not called

### ISSUE THREAD

**Issue by wsh4089** [google/GoogleUtilities#14]
GoogleUtilities/AppDelegateSwizzler (7.2.2)

When I tried to wake up the App using scheme, if the App was running in the background, I found that the method in AppDelegate was not called. Through Debug, it is found that the hook in Google Utilities did not call the original method. Please see the screenshot. I hope it can be resolved as soon as possible. This is a very serious online problem.

![89021616497705_ pic_hd](https://user-images.githubusercontent.com/5722816/112137614-6dd2ea00-8c0b-11eb-884d-b92d92fbe790.jpg)

**Comment by maksymmalyhin** [comment]
@wsh4089 Sorry you encountered the issue.

Could you please provide additional details to help us reproduce it on our end:
- Would it be possible to provide a sample project where the issue is reproducible? It will speed up the investigation significantly.
- I assume it is an iOS app, right?
- is the issue reproducible on a specific iOS version? 
- could you share the relevant part of UIApplicationDelegate

As a temporary workaround you can disable app delegate swizzling - see the [instruction](https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in). If you decide to do so please make sure you follow the manual integration steps for SDKs that rely on the app delegate swizzling like [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/ios/client#token-swizzle-disabled), [Firebase Auth](https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling), etc.

**Comment by wsh4089** [comment]
@maksymmalyhin I checked deeply, and I found that the application delegate was tampered with by ZaiusSDK. They used the proxy method, so that you couldn't get the implementation of the selector when you got it. I'm sorry, but I don't think this is your problem.

**Comment by maksymmalyhin** [comment]
@wsh4089 Thank you for the update.
